import React from 'react'

const MainContianer = () => {
  return (
    <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem aut quibusdam maxime porro distinctio sint earum. Beatae nemo atque excepturi iure iusto obcaecati veniam accusamus dolorem vel. Dolor explicabo nam temporibus omnis perferendis, rerum aut reiciendis, quam commodi quibusdam, accusamus dolorum fugiat praesentium. Ab itaque voluptate earum laboriosam ut? Minima excepturi nam culpa ea reprehenderit ex at debitis sit repellat aspernatur accusamus suscipit voluptatem dignissimos atque laborum quaerat, mollitia facere hic adipisci deleniti rem. Cupiditate vero voluptate expedita corporis, obcaecati sit reiciendis assumenda error vitae blanditiis veniam distinctio id et asperiores ad laborum perspiciatis magnam unde commodi! Dolorem culpa eius cum quia neque fugiat, perferendis esse vitae ipsum, tempora velit corrupti quae rerum cupiditate dolores! Aliquid ab earum, consequatur voluptates aliquam dolorem quam delectus nam iusto aut quibusdam, cum, pariatur mollitia beatae ad accusamus autem sapiente perspiciatis id omnis illo quo sed! Dignissimos libero distinctio itaque, fuga, quis iusto cum soluta sequi ratione expedita repellendus consectetur error ab aut necessitatibus officiis rerum accusantium natus, voluptas voluptatum assumenda facere ipsa enim. Reiciendis possimus beatae atque fuga nam nobis asperiores neque inventore quo, hic, nemo at sed distinctio aperiam. Dolor, provident aliquid. Voluptatum quibusdam omnis quos eius ratione quaerat fugit laboriosam dolore impedit, atque accusamus minus autem maiores ab ex ullam laborum vitae nobis voluptatibus excepturi modi necessitatibus. Nostrum velit iste deleniti quos nihil nesciunt cupiditate amet molestiae optio necessitatibus architecto sequi nemo odit officia aspernatur nulla laudantium corporis magnam eius omnis, mollitia debitis aliquam laborum. Expedita ratione libero magnam minus eligendi?</p>
        <br />
        <hr />
        <br />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores vel aliquam dolor harum ipsum maxime odio est delectus quisquam, laudantium optio, praesentium quos officia aut nobis totam id eligendi iste qui hic? Architecto natus repudiandae non quisquam eligendi quibusdam neque aliquid est sint pariatur quidem ut veritatis, minus vitae suscipit at amet aspernatur asperiores voluptatem et nam totam quasi provident! Exercitationem dolorem earum nemo voluptatibus distinctio quibusdam. Nesciunt similique, ullam quidem, minus corrupti maxime nulla vero nihil vitae eveniet incidunt eligendi repellat veritatis quisquam esse natus nisi? Incidunt, ullam aut, assumenda in ea harum adipisci aperiam voluptates molestiae iusto vero. Excepturi nisi debitis non voluptates animi suscipit porro repudiandae, est molestiae praesentium odit nostrum, perferendis provident error voluptas quas delectus et ex, expedita maiores minima officia dolor magnam tenetur. Fuga, repellendus exercitationem necessitatibus facilis qui sit eligendi nisi eius repudiandae maxime culpa, cupiditate incidunt rem aliquid modi odio reprehenderit! Laudantium sint, reprehenderit iure accusantium similique debitis officiis molestiae cumque consequatur eos temporibus distinctio facilis. Quaerat obcaecati animi porro beatae. Numquam molestias alias reprehenderit odit hic voluptatum fugiat architecto dolore nostrum, officia possimus neque distinctio. Odio fuga reiciendis blanditiis omnis unde illo laborum corporis excepturi illum quibusdam? Harum magnam sapiente eveniet laboriosam impedit non animi nesciunt eius nam, quo ex sit. Vel qui similique perferendis dicta libero optio culpa ratione. Deserunt facilis exercitationem laborum doloribus omnis officia ullam commodi, alias nihil sint cupiditate adipisci tenetur vitae magnam dolorum rem dolore dolores enim atque doloremque excepturi explicabo iure. Animi atque laboriosam a, architecto eius minus similique vero placeat accusantium exercitationem qui totam vel adipisci commodi dignissimos nisi quisquam temporibus, ex alias laborum facere nobis debitis? Laboriosam totam dicta, maxime fugit obcaecati deserunt rem deleniti, ea, dolores iure sed? Accusantium blanditiis iste ut praesentium nobis eveniet vitae. Delectus minima nihil perferendis ab voluptates.</p>
        <br />
        <br />
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis, laudantium neque temporibus nobis quaerat consequuntur odit officiis sapiente hic non accusantium excepturi sit quo ullam autem incidunt molestias fugiat tempora qvis distinctio molestiae, obcaecati quod nisi ducimus eum, omnis cum voluptatum, veritatis a cupiditate! Vel incidunt mollitia odio quo dolores numquam vero accusantium.</p>
    </div>
  )
}

export default MainContianer